#!/bin/bash

set -e

((!$#)) && echo 'fatal: branch name required' && exit 1

function cleanup {
  git checkout -q master --
}
trap cleanup EXIT

git checkout -q "$1" --
git merge -q master
git checkout -q master
if [[ $(git diff "$1" --) ]]; then
  git diff "$1" -- >&2
  exit 1
else
  git branch -D "$1" --
fi
