#!/usr/bin/env zsh
#
# Find a file in a git repository by regex.
# Ex:
#   pop BaseViewController.scala | xargs git blame
#   vim `pop Base.*Controller.scala`

FILES_CMD="git ls-files | uniq | grep -i $1"
LINES=`eval $FILES_CMD | wc -l`
if [ "$LINES" -eq 0 ]; then
  echo
elif [ "$LINES" -gt 1 ]; then
  eval $FILES_CMD >&2
  exit 1
else
  eval $FILES_CMD
fi
