#!/usr/bin/env python2
#
# Removes duplicate entries from $PATH
# Example usage:
#   At end of .bashrc/.zshrc:
#     PATH=`trimpath "$PATH"`

import os, sys

if len(sys.argv) <= 1 :
  print 'Usage: trimpath PATH'
  exit(0)

path = sys.argv[1]

items = path.split(':')
new_items = []
for item in items :
  if item not in new_items :
    new_items.append(item)

print ':'.join(new_items)
