#!/usr/bin/env zsh
#
# Open files in directory based off partial names
# Ex:
#   Open all controllers
#     vif controller

FILES_CMD="find . | uniq | grep -i $1 2>/dev/null"
LINES=`eval $FILES_CMD | wc -l`
if [ "$LINES" -eq 0 ]; then
  echo
elif [ "$LINES" -gt 3 ]; then
  eval $FILES_CMD
else
  exec vim -O `eval $FILES_CMD`
fi
