#!/usr/bin/env zsh
#
# Like vif, but with no 3 file limit

FILES_CMD="find . | uniq | grep -i $1 2>/dev/null"
LINES=`eval $FILES_CMD | wc -l`
if [ "$LINES" -eq 0 ]; then
  echo
else
  exec vim -O `eval $FILES_CMD`
fi
