#!/usr/bin/env bash
#
# Open files in git repository based off partial names
# Ex:
#   Open all controllers
#     vig controller

export IFS=$'\n'
LINES=($(git ls-files | uniq | grep -i $1))
LINES_COUNT=${#LINES[@]}

if [ "$LINES_COUNT" -eq 0 ]; then
  echo
elif [ "$LINES_COUNT" -gt 3 ]; then
  for LINE in ${LINES[@]}; do
    echo $LINE
  done
else
  exec vim -O "${LINES[@]}"
fi
